### ISSUE TITLE
Problem building AMReX as a shared library with CMake on MacOS

### ISSUE THREAD

**Issue by RemiLehe** [AMReX-Codes/amrex#425]
When trying to build AMReX as a **shared library** on **MacOS**, I am getting a compilation error ; the same error was also reported by @MaxThevenet in off-line discussion.

More precisely, when running:
```
mkdir builddir
cd builddir
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DBUILD_SHARED_LIBS=ON ..
make install
```
I get
```
[100%] Linking CXX shared library libamrex.dylib
Undefined symbols for architecture x86_64:
  "getLevelBld()", referenced from:
      amrex::Amr::InitAmr()    in AMReX_Amr.cpp.o
  "_amrex_probinit", referenced from:
      amrex::Amr::readProbinFile(int&)  in AMReX_Amr.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [Src/libamrex.dylib] Error 1
make[1]: *** [Src/CMakeFiles/amrex.dir/all] Error 2
make: *** [all] Error 2
```
This error does not occur when compiling AMReX as *a static library* (i.e. removing `-DBUILD_SHARED_LIBS=ON`). Also, I am able to build AMReX as a shared library **on Ubuntu** (as opposed to MacOS).

**Comment by WeiqunZhang** [comment]
I think we have the following options.

1. Pass option `-undefined dynamic_lookup` to cmake to tell it to ignore undefined symbols.  But this may cause problems by ignoring other undefined symbols that should not be ignored.

2. Or, fix AMReX by storing function pointers to `amrex_probinit` and `geLevelBld` instead of declaring them extern functions.  But this will break `class AmrLevel` based applications codes and require them to fix.

3. Or, use `__attribute__((weak))` to declare `void __attribute__((weak)) amrex_probinit(...)` and `extern __attribute__(weak) amrex::LevelBld* getLevelBld();`.  But this attribute is a compiler extension.  So it may not work for every compiler.

Remi, could you please try option 3 to see if it fixes the problem?  I don't have a Mac to test.  You need to modify `AMReX_PROB_AMR_F.H` and `AMReX_LevelBld.H` in `Src/Amr`.

**Comment by mic84** [comment]
A fix has been pushed to development branch

**Comment by RemiLehe** [comment]
Thanks for introducing the above fix.
However, I am now getting the following error:
```
[100%] Linking CXX shared library libamrex.dylib
ld: can't use -undefined warning or suppress with -twolevel_namespace
collect2: error: ld returned 1 exit status
make[2]: *** [Src/libamrex.dylib] Error 1
make[1]: *** [Src/CMakeFiles/amrex.dir/all] Error 2
make: *** [all] Error 2
```
Any suggestion how to fix this?

**Comment by mic84** [comment]
Unfortunately I don't have a Mac to reproduce this bug. I managed to test the previous fix on a colleague's Mac and we did not have any issue with it.

**Comment by WeiqunZhang** [comment]
@RemiLehe Did you try `__attribute__((weak))` with amrex before the latest cmake change?

**Comment by ax3l** [comment]
Problem persists even with `__attribute__((weak))`/`__attribute__((weak_import)` - investigation ongoing in #1836

**Comment by ax3l** [comment]
@WeiqunZhang since the weak-symbol approach is not very portable, do you think we could mid-term approach [option2](https://github.com/AMReX-Codes/amrex/issues/425#issuecomment-473085827) that you mentioned?

It's a breaking change, but probably worth it for portability. cc @sayerhs 

From what I found, weak symbols are problematic on:
- macOS: hackery (see #1836)
- FreeBSD (unclear)
- Windows: fully unsupported (no `.dll`s possible)

**Comment by WeiqunZhang** [comment]
Another possibility is to not include `Amr/` if shared library is enabled.  WarpX does not need anything from the `Amr/` directory.

**Comment by WeiqunZhang** [comment]
What about support both the current way and a new function pointer based approach in the source code with a macro  For building into a library, we use the function pointer based approach, otherwise use the old approach.  Codes that depend on the current behavior are unlikely using amrex as a library at the moment.  If they do in the future, they can switch.
