### ISSUE TITLE
Cmake root access

### ISSUE THREAD

**Issue by matt-frey** [AMReX-Codes/amrex#57]
When trying to configure with cmake I obtain the error:
```
CMake Error: Could not open file for write in copy operation /usr/local/bin/Makefile.export.tmp
CMake Error: : System Error: Permission denied
CMake Error at Tools/CMake/InstallManager.cmake:214 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:114 (create_exports)
```
#### Configure procedure:
```
git clone https://github.com/AMReX-Codes/amrex.git
cd amrex; mkdir build; cd build;
CXX=$MPICXX CC=$MPICC cmake -DENABLE_PARTICLES=1 -DENABLE_MG_BOXLIB=1 ../
```

The configure output is [cmake-configure-output.txt](https://github.com/AMReX-Codes/amrex/files/1154830/cmake-configure-output.txt) and the log file of cmake is [CMakeOutput.txt](https://github.com/AMReX-Codes/amrex/files/1154834/CMakeOutput.txt)

The issue only occurs if ```CMAKE_INSTALL_PREFIX``` points to a directory that requires root access, i.e. ```sudo``` is needed.

#### Modules:
* cmake/3.6.3
* gcc/5.4.0
* openmpi/1.10.4

#### OS:
* Ubuntu/16.04

**Comment by mic84** [comment]
CMAKE_INSTALL_PREFIX has to be provided by the user, otherwise it defaults to /usr/local which is a system directory and therefore requires root access. A fix has been committed to the development branch:   CMAKE_INSTALL_PREFIX will now default to /path/to/amrex/installdir if the user does not  provide a custom installation path.

**Comment by matt-frey** [comment]
I normally install my external packages under /opt/ that requires also root access. In that case I would specify ```-DCMAKE_INSTALL_PREFIX=/opt/amrex``` in the 'cmake' command.
Unfortunately, an installation of AMReX in a root directory fails.

**Comment by mic84** [comment]
Hello  Matt,

I am on Ubuntu 14.04 and I successfully installed AMReX in /opt. Perhaps
you are forgetting to use "sudo" before each command involved in the
installation:

*sudo cmake  <cmake-config-flags> -DCMAKE_INSTALL_PREFIX=path/to/installdir
    /path/to/amrex/folder*
*sudo make install*

Please let me know if you still have issues with that.

Michele

**Comment by matt-frey** [comment]
Hi Michele

I'm still having issues although putting "sudo" for every command. In that case I get an 'undefined reference' to some MPI call.

```
../../../Src/libcboxlib.a(AMReX_BLBackTrace.cpp.o): In function `MPI::Intracomm::Intracomm()':
/usr/lib/openmpi/include/openmpi/ompi/mpi/cxx/intracomm.h:25: undefined reference to `MPI::Comm::Comm()'
```
It works fine when installing to a non-root directory. I do not understand this.

Best,
Matthias

**Comment by mic84** [comment]
Hi Matt,

could you send me the full log, i.e. the complete output when you issue
cmake and the the complete output of "make install VERBOSE=1"?
'VERBOSE=1' is to make sure all the build infos are printed out.
Thanks,
Michele

**Comment by matt-frey** [comment]
The output of 'sudo make install VERBOSE=1' is in [output.txt](https://github.com/AMReX-Codes/amrex/files/1160221/output.txt) and the log file of 'cmake' is in 
[CMakeOutput.txt](https://github.com/AMReX-Codes/amrex/files/1160226/CMakeOutput.txt). Additionally, the cmake cache file [CMakeCache.txt](https://github.com/AMReX-Codes/amrex/files/1160227/CMakeCache.txt).

Best,
Matthias

**Comment by mic84** [comment]
Matt,

could you try to compile with MPICH instead of OpenMPI and see if that
solves your problem?

Thanks,
Michele

**Comment by matt-frey** [comment]
I don't think it's an issue of the usage of OpenMPI since I'm able to install the library for a non-root directory, furthermore, till the commit bc336d8245746dd317ae554bd8a48f6b4a794439 I could install it in a root directory.

**Comment by mic84** [comment]
Matt,
the file you sent (output.txt) shows there is an error at link time. Using
sudo solved the permissions problem you had initially.
Please try with MPICH and let us know.

Michele

**Comment by matt-frey** [comment]
It works with MPICH.

Best,
Matthias
