### ISSUE TITLE
Plot tools unable to build with CMake when CUDA is enabled

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#748]
When trying to build `fcompare` when CUDA is enabled using CMake, I get the errors below. I also get errors regarding `AMREX_PRAGMA_SIMD`.
```
In file included from /home/jrood/exawind/amr-wind/submods/amrex/Src/Base/AMReX.H:5:0,
                 from /home/jrood/exawind/amr-wind/submods/amrex/Src/Base/AMReX_Array.H:11,
                 from /home/jrood/exawind/amr-wind/submods/amrex/Tools/Plotfile/AMReX_PPMUtil.H:5,
                 from /home/jrood/exawind/amr-wind/submods/amrex/Tools/Plotfile/AMReX_PPMUtil.cpp:2:
/home/jrood/exawind/amr-wind/submods/amrex/Src/Base/AMReX_GpuQualifiers.H:13:31: error: ‘__host__’ does not name a type; did you mean ‘__loff_t’?
 #define AMREX_GPU_HOST_DEVICE __host__ __device__
```

**Comment by WeiqunZhang** [comment]
The GNU make system has a similar issue of compiling these tools for CUDA.  The problem there is it tries to generate the final executables with

```
COMPILER  .... main_a.cpp  x.o y.o z.o
COMPILER  .... main_b.cpp  x.o y.o z.o
```

We did it this way because we have multiple executables and they share most .o files except for the one from their own cpp file.  This works when `COMPILER` is gcc, but not for nvcc.  I have fixed the GNU make file (but not CMake) by compiling `main_a.cpp` into `.o` first and then linking.  I think CMake fails for a similar reason.

**Comment by mic84** [comment]
@jrood-nrel Support for compiling plotfiles tool for CUDA is now implemented in CMake as well. Thank you for reporting this.

**Comment by jrood-nrel** [comment]
I tested this today and I'm still getting errors from `fcompare` when using CUDA. Mostly these:
```
error: calling a constexpr __host__ function("operator()") from a __device__ function("operator()") is not allowed
```
It looks like there are some command line options the output is recommending like:
```
error: __host__ or __device__ annotation on lambda requires --expt-extended-lambda nvcc flag
```

**Comment by mic84** [comment]
@jrood-nrel are you using CMake or GNUMake? I am unable to reproduce the issue you encountered if I build with CMake.

**Comment by jrood-nrel** [comment]
I'm using CMake. I'm using GCC 7.4.0 or 8.3.0 and I see the errors with CUDA 9.2.88, 10.0.130, and 10.1.128. My AMReX commit is `5ba96e09f85ecb4cd961d5b43b4cb51f7f5d396f`.

**Comment by mic84** [comment]
Can you please send me the full output of the cmake command?

**Comment by jrood-nrel** [comment]
Sure. I am using AMReX as a submodule in my project. This script below reproduces the error for me when I try to build `fcompare`:
```
git clone --recursive https://github.com/Exawind/amr-wind.git
cd amr-wind && mkdir build && cd build 
cmake -DAMR_WIND_ENABLE_CUDA:BOOL=ON \
      -DCUDA_ARCH:STRING=7.0 \
      -DAMR_WIND_ENABLE_FCOMPARE:BOOL=ON \
      .. && make -j 12 fcompare
```

**Comment by mic84** [comment]
The issue you are experiencing is due to the way AMReX is included as a subproject. Exa-wind CMake setup adds the top-level AMReX directory and, separately, the `Tools/Plotfile/` subdirectory.  The targets defined in the latter, including `fcompare`, are then built by the top level project, i.e. Exa-wind, and not by AMReX CMake. This, in turn, makes `fcompare` unaware of the proper flags for CUDA compilation. I created a pull request with a fix (# 64) in the Exa-Wind repo. I am closing this issue since no fix is required on our part.

**Comment by jrood-nrel** [comment]
Thanks @mic84 ! Sorry it was my mistake causing this.
